In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns
# from ydata_profiling import ProfileReport 

df = pd.read_csv('insurance.csv')

df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
profile = ProfileReport(df, title="Insurance Dataset Profiling Report", explorative=True)

profile.to_file("insurance_eda_report.html")

profile.to_notebook_iframe()

In [2]:
df = df.drop_duplicates()

In [ ]:
sns.boxplot(x="children", y="charges", data=df)
plt.title("Charges by Number of Children")
plt.show()

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le = LabelEncoder()
df.loc[:, 'sex'] = le.fit_transform(df['sex'])
df.loc[:, 'smoker'] = le.fit_transform(df['smoker'])

In [9]:
#df = pd.get_dummies(df, columns=['region'], drop_first=True)

In [5]:
le = LabelEncoder()
df.loc[:, 'region'] = le.fit_transform(df['region'])

In [6]:
df.to_csv("Insurance2.csv")

In [7]:
X = df.drop('charges', axis=1)
y = df['charges']

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Linear Regression MAE:", mean_absolute_error(y_test, y_pred_lr))
print("Linear Regression MSE:", mean_squared_error(y_test, y_pred_lr))
print("Linear Regression R2 Score:", r2_score(y_test, y_pred_lr))
# print("Linear Regression RMSE:", mean_squared_error(y_test, y_pred_lr, squared=False))

Linear Regression MAE: 4182.353155288297
Linear Regression MSE: 35493102.61165053
Linear Regression R2 Score: 0.8068466322629111

In [14]:
import joblib

model_name='linear_regression_model2.pkl'
# Save the trained model
joblib.dump(lr, model_name)
print(f"Model saved as {model_name}")

model_1= joblib.load(model_name)

y_pred_lr2 = model_1.predict(X_test)
print("Linear Regression MAE:", mean_absolute_error(y_test, y_pred_lr2))
print("Linear Regression MSE:", mean_squared_error(y_test, y_pred_lr2))
print("Linear Regression R2 Score:", r2_score(y_test, y_pred_lr2))
#print("Linear Regression RMSE:", mean_squared_error(y_test, y_pred_lr2, squared=False))

Model saved as linear_regression_model2.pkl
Linear Regression MAE: 4182.353155288297
Linear Regression MSE: 35493102.61165053
Linear Regression R2 Score: 0.8068466322629111

In [19]:
X_test

      age sex     bmi  children smoker region
900    49   1  22.515         0      0      0
1064   29   0  25.600         4      0      3
1256   51   0  36.385         3      0      1
298    31   1  34.390         3      1      1
237    31   1  38.390         2      0      2
...   ...  ..     ...       ...    ...    ...
534    64   1  40.480         0      0      2
542    63   0  36.300         0      0      2
760    22   0  34.580         2      0      0
1284   61   1  36.300         1      1      3
1285   47   0  24.320         0      0      0

[268 rows x 6 columns]

In [29]:
age = int(23)
bmi = float(25.3)
children = int(2)
sex = 'male'
smoker = 'no'
region = 'northwest'

print(f"{age},{bmi},{children}, {sex}, {smoker}, {region}")

#         return jsonify({'predicted_charges': age})


label_mapping = {'male': 0, 'female': 1, 'no': 0, 'yes': 1, 'southwest': 0, 'southeast': 1, 'northwest': 2, 'northeast': 3}

sex = label_mapping.get(sex, -1)
smoker = label_mapping.get(smoker, -1)
region = label_mapping.get(region, -1)

print(f"sex {sex}, smoker-{smoker} , region - {region}")


input_data = pd.DataFrame([[age,sex, bmi, children,  smoker, region]],
                                  columns=['age','sex', 'bmi', 'children', 'smoker', 'region'])

23,25.3,2, male, no, northwest
sex 0, smoker-0 , region - 2

In [30]:
input_data

   age  sex   bmi  children  smoker  region
0   23    0  25.3         2       0       2

In [31]:
X_test

      age sex     bmi  children smoker region
900    49   1  22.515         0      0      0
1064   29   0  25.600         4      0      3
1256   51   0  36.385         3      0      1
298    31   1  34.390         3      1      1
237    31   1  38.390         2      0      2
...   ...  ..     ...       ...    ...    ...
534    64   1  40.480         0      0      2
542    63   0  36.300         0      0      2
760    22   0  34.580         2      0      0
1284   61   1  36.300         1      1      3
1285   47   0  24.320         0      0      0

[268 rows x 6 columns]

In [32]:
result=model_1.predict(input_data)
result

array([3175.88737285])

In [15]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

In [ ]:
poly = make_pipeline(PolynomialFeatures(degree=2), LinearRegression())
poly.fit(X_train, y_train)

In [ ]:
y_pred_poly = poly.predict(X_test)
print("Polynomial Regression MAE:", mean_absolute_error(y_test, y_pred_poly))
print("Polynomial Regression MSE:", mean_squared_error(y_test, y_pred_poly))
print("Polynomial Regression R2 Score:", r2_score(y_test, y_pred_poly))
print("Polynomial Regression RMSE:", mean_squared_error(y_test, y_pred_poly, squared=False))

In [ ]:
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred_lr, color='blue', label='Linear Regression Predictions')
plt.scatter(y_test, y_pred_poly, color='orange', label='Polynomial Regression Predictions')
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--', label='Perfect Prediction')
plt.xlabel('Actual Charges')
plt.ylabel('Predicted Charges')
plt.title('Actual vs Predicted Charges')
plt.legend()
plt.show()

In [ ]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)
print("Decision Tree Regression MAE:", mean_absolute_error(y_test, y_pred_dt))
print("Decision Tree Regression MSE:", mean_squared_error(y_test, y_pred_dt))
print("Decision Tree Regression R2 Score:", r2_score(y_test, y_pred_dt))
print("Decision Tree Regression RMSE:", mean_squared_error(y_test, y_pred_dt, squared=False))

In [ ]:
 from sklearn.ensemble import RandomForestRegressor
    
rf = RandomForestRegressor(random_state=42, n_estimators=100)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
print("Random Forest Regression MAE:", mean_absolute_error(y_test, y_pred_rf))
print("Random Forest Regression MSE:", mean_squared_error(y_test, y_pred_rf))
print("Random Forest Regression R2 Score:", r2_score(y_test, y_pred_rf))
print("Random Forest Regression RMSE:", mean_squared_error(y_test, y_pred_rf, squared=False))

In [ ]:
plt.figure(figsize=(12, 8))
plt.scatter(y_test, y_pred_lr, color='blue', alpha=0.6, label='Linear Regression Predictions')
plt.scatter(y_test, y_pred_poly, color='orange', alpha=0.6, label='Polynomial Regression Predictions')
plt.scatter(y_test, y_pred_dt, color='green', alpha=0.6, label='Decision Tree Predictions')
plt.scatter(y_test, y_pred_rf, color='purple', alpha=0.6, label='Random Forest Predictions')
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--', label='Perfect Prediction')
plt.xlabel('Actual Charges')
plt.ylabel('Predicted Charges')
plt.title('Actual vs Predicted Charges (Regression Models)')
plt.legend()
plt.show()

In [22]:
from sklearn.model_selection import GridSearchCV

In [ ]:
poly_params = {
    'polynomialfeatures__degree': [2, 3, 4]
}

poly_grid = GridSearchCV(make_pipeline(PolynomialFeatures(), LinearRegression()), poly_params, cv=5, scoring='r2')
poly_grid.fit(X_train, y_train)
print("Best params for Poly Reg:", poly_grid.best_params_)
poly_best = poly_grid.best_estimator_

In [ ]:
dt_params = {
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

dt_grid = GridSearchCV(DecisionTreeRegressor(random_state=42), dt_params, cv=5, scoring='r2')
dt_grid.fit(X_train, y_train)
print("Best params for DT:", dt_grid.best_params_)
dt_best = dt_grid.best_estimator_

In [ ]:
rf_params = {
    'n_estimators': [50, 100, 150],
    'criterion': ['squared_error', 'absolute_error'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10]
}

rf_grid = GridSearchCV(RandomForestRegressor(random_state=42), rf_params, cv=5, scoring='r2')
rf_grid.fit(X_train, y_train)
print("Best params for RF:", rf_grid.best_params_)
rf_best = rf_grid.best_estimator_

In [26]:
def evaluate_model(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    print(f"{model_name} MAE:", mean_absolute_error(y_test, y_pred))
    print(f"{model_name} MSE:", mean_squared_error(y_test, y_pred))
    print(f"{model_name} R2 Score:", r2_score(y_test, y_pred))
    print(f"{model_name} RMSE:", mean_squared_error(y_test, y_pred, squared=False))
    return y_pred

In [ ]:
y_pred_poly_best = evaluate_model(poly_best, X_test, y_test, "Tuned Poly Reg")

In [ ]:
y_pred_dt_best = evaluate_model(dt_best, X_test, y_test, "Tuned DT")

In [ ]:
y_pred_rf_best = evaluate_model(rf_best, X_test, y_test, "Tuned RF")

In [ ]:
plt.figure(figsize=(12, 8))
plt.scatter(y_test, y_pred_dt_best, color='green', alpha=0.6, label='Tuned DT Predictions')
plt.scatter(y_test, y_pred_rf_best, color='purple', alpha=0.6, label='Tuned RF Predictions')
plt.scatter(y_test, y_pred_poly_best, color='orange', alpha=0.6, label='Tuned Poly Reg Predictions')
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--', label='Perfect Prediction')
plt.xlabel('Actual Charges')
plt.ylabel('Predicted Charges')
plt.title('Actual vs Predicted Charges (Tuned Models)')
plt.legend()
plt.show()

In [ ]:
import joblib

# Save the trained model
joblib.dump(lr, 'linear_regression_model.pkl')
print("Model saved as linear_regression_model.pkl")